version: "3.8"
services:
  askgpt:
    ports:
      - 5000:5000
    environment:
      - PYTHONUNBUFFERED=1 # send output to terminal
      - RUNTIME_ENV=prod

    entrypoint:
      - pixi
      - run
      - gunicorn

    command:
      - "askgpt.app.app:app_factory"
      - "--workers"
      - "1"
      - "-k"
      - "uvicorn.workers.UvicornWorker"
      - "--bind"
      - "localhost:5000"

    healthcheck:
      test: ["CMD", "curl", "-f", "http://0.0.0.0:5000/v1/health/"]
      interval: 10s
      timeout: 5s
      retries: 5

    restart: unless-stopped
    build:
      context: ./backend
      dockerfile: Dockerfile

    volumes:
      - ./backend/askgpt/settings.toml:/app/settings.toml

  redis:
    image: redis:latest # Use the official Redis image
    ports:
      - "6379:6379" # Map port 6379 on the host to port 6379 in the container
    command:
      - redis-server
      - --bind
      - 0.0.0.0

  # frontend:
  #   ports:
  #     - 3000:3000
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile
  #   volumes:
  #     - ./frontend:/app
  #   labels:
  #     - "traefik.enable=true"
  #     - "traefik.http.routers.frontend.rule=Host(`frontend.example.com`)"
  #     - "traefik.http.services.frontend.loadbalancer.server.port=3000"
# networks:
#   default:
#     external:
#       name: traefik_default
