version: "3.8"
services:
  askgpt:
    ports:
      - 5000:5000
    environment:
      - PYTHONUNBUFFERED=1  # send output to terminal 
      - RUNTIME_ENV=prod

    entrypoint:
      - pixi
      - run
      - gunicorn

    command: 
      - "src.server:app_factory"
      - "--workers"
      - "1"
      - "-k"
      - "uvicorn.workers.UvicornWorker"
      - "--bind"
      - "0.0.0.0:5000"

    restart: unless-stopped
    build:
      context: ./backend
      dockerfile:
        Dockerfile

    volumes:
      - ./backend/src/settings.toml:/app/settings.toml


