# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: llama.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bllama.proto\x12\x05llama\"%\n\x11\x43ompletionRequest\x12\x10\n\x08question\x18\x01 \x01(\t\"(\n\x12\x43ompletionResponse\x12\x12\n\ncompletion\x18\x01 \x01(\t2T\n\x11\x43ompletionService\x12?\n\x08\x43omplete\x12\x18.llama.CompletionRequest\x1a\x19.llama.CompletionResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'llama_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_COMPLETIONREQUEST']._serialized_start=22
  _globals['_COMPLETIONREQUEST']._serialized_end=59
  _globals['_COMPLETIONRESPONSE']._serialized_start=61
  _globals['_COMPLETIONRESPONSE']._serialized_end=101
  _globals['_COMPLETIONSERVICE']._serialized_start=103
  _globals['_COMPLETIONSERVICE']._serialized_end=187
# @@protoc_insertion_point(module_scope)
